import { ArrowRight, Minus, Plus, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'

export default function CartPage() {
  const { cart, updateQuantity, removeFromCart, showToast } = useApp()
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const tax = subtotal * .08
  return <section className="cart-page page-section"><p className="eyebrow">Your selection</p><h1 className="page-title">YOUR CART</h1>{cart.length ? <div className="cart-layout"><div className="cart-items">{cart.map((item) => <article className="cart-item" key={`${item.product.id}-${item.size}`}><div className="cart-visual" style={{ '--accent': item.product.accent }} /><div className="cart-item-copy"><p className="eyebrow">{item.product.category}</p><h2>{item.product.name}</h2><p className="muted">{item.size} · ${item.price.toFixed(2)}</p><div className="quantity-control"><button aria-label="Decrease quantity" onClick={() => updateQuantity(item.product.id, item.quantity - 1, item.size)}><Minus size={13} /></button><span>{item.quantity}</span><button aria-label="Increase quantity" onClick={() => updateQuantity(item.product.id, item.quantity + 1, item.size)}><Plus size={13} /></button></div></div><strong className="cart-line-total">${(item.price * item.quantity).toFixed(2)}</strong><button className="remove-button" aria-label={`Remove ${item.product.name}`} onClick={() => { removeFromCart(item.product.id, item.size); showToast(`${item.product.name} removed from your cart.`) }}><Trash2 size={16} /></button></article>)}</div><aside className="summary-panel"><p className="eyebrow">Summary</p><div><span>Subtotal</span><strong>${subtotal.toFixed(2)}</strong></div><div><span>Tax · 8%</span><strong>${tax.toFixed(2)}</strong></div><div className="summary-total"><span>Total</span><strong>${(subtotal + tax).toFixed(2)}</strong></div><Link className="button button-light" to="/checkout">Checkout <ArrowRight size={15} /></Link></aside></div> : <div className="empty-cart"><div className="empty-mark">AB</div><h2>Your coffee ritual<br /><em>starts here.</em></h2><p className="muted">A good day can begin with one considered choice.</p><Link className="button button-light" to="/menu">Explore menu</Link></div>}</section>
}
