import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'

export default function CheckoutPage() {
  const { cart, user, placeOrder, showToast } = useApp(); const navigate = useNavigate()
  const [submitted, setSubmitted] = useState(null); const [form, setForm] = useState({ name: user?.name || '', email: user?.email || '', phone: '', type: 'Pickup', address: '', city: 'Karachi', payment: 'Cash on Pickup' }); const [errors, setErrors] = useState({})
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const tax = subtotal * .08
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = (event) => { event.preventDefault(); const next = {}; if (!form.name.trim()) next.name = 'Please enter your name.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = 'Please enter a valid email.'; if (!form.phone.trim()) next.phone = 'Please enter your phone number.'; if (form.type === 'Delivery' && !form.address.trim()) next.address = 'Please enter your delivery address.'; if (Object.keys(next).length) { setErrors(next); return } const order = placeOrder({ customer: { name: form.name, email: form.email, phone: form.phone }, type: form.type, address: form.type === 'Delivery' ? `${form.address}, ${form.city}` : '', payment: form.payment }); setSubmitted(order); showToast('Order placed successfully.') }
  if (submitted) return <section className="success-page page-section"><div className="success-icon"><Check size={25} /></div><p className="eyebrow">Order confirmed</p><h1 className="page-title">YOUR COFFEE<br /><em>IS ON ITS WAY.</em></h1><p className="muted">Order {submitted.id} · {submitted.type} · ${submitted.total.toFixed(2)}</p><div className="success-actions"><button className="button button-light" onClick={() => navigate('/orders')}>View order <ArrowRight size={15} /></button><Link className="back-link" to="/">Back to home</Link></div></section>
  if (!cart.length) return <section className="page-section"><p className="eyebrow">Checkout</p><h1 className="page-title">Your cart is empty.</h1><Link className="button button-light" to="/menu">Explore menu</Link></section>
  return <section className="checkout-page page-section"><Link className="back-link" to="/cart"><ArrowLeft size={15} /> Return to cart</Link><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><p className="eyebrow">Almost there</p><h1 className="page-title">CHECKOUT</h1><p className="demo-note">Demo checkout — no real payment will be processed.</p><fieldset><legend>01 / Contact information</legend><label>Full name<input name="name" value={form.name} onChange={update} placeholder="Your full name" />{errors.name && <small className="form-error">{errors.name}</small>}</label><label>Email<input name="email" type="email" value={form.email} onChange={update} placeholder="you@example.com" />{errors.email && <small className="form-error">{errors.email}</small>}</label><label>Phone<input name="phone" value={form.phone} onChange={update} placeholder="+92 300 0000000" />{errors.phone && <small className="form-error">{errors.phone}</small>}</label></fieldset><fieldset><legend>02 / Pickup or delivery</legend><div className="choice-row">{['Pickup', 'Delivery'].map((type) => <label className={`choice ${form.type === type ? 'active' : ''}`} key={type}><input type="radio" name="type" value={type} checked={form.type === type} onChange={update} />{type}</label>)}</div>{form.type === 'Delivery' && <div className="address-fields"><label>Address<input name="address" value={form.address} onChange={update} placeholder="Street and building" />{errors.address && <small className="form-error">{errors.address}</small>}</label><label>City<input name="city" value={form.city} onChange={update} /></label></div>}</fieldset><fieldset><legend>03 / Payment method</legend><div className="choice-row">{['Cash on Pickup', 'Card'].map((payment) => <label className={`choice ${form.payment === payment ? 'active' : ''}`} key={payment}><input type="radio" name="payment" value={payment} checked={form.payment === payment} onChange={update} />{payment}</label>)}</div>{form.payment === 'Card' && <p className="muted safe-card">Safe demo card fields only. Do not enter a real card number.<br />Card ending in 4242 · Exp. 12/30</p>}</fieldset><button className="button button-light" type="submit">Place order <ArrowRight size={15} /></button></form><aside className="checkout-summary summary-panel"><p className="eyebrow">Order summary</p>{cart.map((item) => <div key={`${item.product.id}-${item.size}`}><span>{item.product.name} <small>× {item.quantity}</small></span><strong>${(item.price * item.quantity).toFixed(2)}</strong></div>)}<div><span>Tax</span><strong>${tax.toFixed(2)}</strong></div><div className="summary-total"><span>Total</span><strong>${(subtotal + tax).toFixed(2)}</strong></div></aside></div></section>
}
